name: build page

on:
  push:
    branches:
      - main # Adjust this if your default branch is not 'main'

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install    
        working-directory: ./ # Ensure this points to the directory containing package.json
      - name: Generate build
        run: npm run build
        env:
          CI: false
        working-directory: ./ # Ensure this points to the directory containing package.json
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist # Folder to deploy
          publish_branch: gh-pages # Target branch for GitHub Pages
